---
title: "\"Queued Up\" Supplementary App"
subtitle: |
  | Final Project 
  | Data Visualization (STAT 302)
author: "Reed Malcolm"
date: today

format:
  html:
    toc: true
    embed-resources: true
---

::: {.callout-tip icon="false"}
## Github Repo Link


[Final Project GitHub Repo Link](https://github.com/malcor21/stat-302-final.git)
:::

## Introduction

Unanticipated growth in electricity demand---widely attributed to new investments in
AI, manufacturing facilities, and data centers---has driven interest in the US 
power grid among researchers and policymakers in recent years. This has come at a critical
time for the grid as extreme weather events, infrastructural upgrades, and renewable
energy integration present further transmission challenges. To ensure clean, cheap electricity
into the future, advocates say, the grid's material and governance foundations must
undergo urgent reforms. 

Currently, a flood of primarily renewable energy projects are 
seeking approval to connect to the grid and eventually begin providing power, waiting in a limbo
known as the interconnection queue. "Queued Up 2024", a report prepared by the 
Lawrence Berkeley National Laboratory's Energy Markets & Policy department,
conducts a thorough analysis of the past and current functioning of the interconnection
queue. In addition to a PowerPoint briefing, the "Queued Up 2024" report provides
readers with a foundational dataset that I used for this final project.
While the briefing also incorporates a polished interactive data visualization portal,
not all aspects of the "Queued Up 2024" dataset are translated into that format.[^1] The
aim of this project was therefore to create a supplementary ShinyApp for interactive
data visualization of those untranslated measures. I focused on interconnection queue residence times and approval
rates, particularly across the US's grid regions, to reinforce the importance of
electric grid reform today.

## Tab 1: Interconnection Queue by Region

### Subtab 1: Mainland US Map

I first created a map of active projects (or capacity) in the interconnection queue
by US grid region. While a figure like this was included in the original "Queued Up"
report and interactive module, I thought it would nevertheless be helpful to frame the following
figures. 

A comprehensive shapefile of US grid regions was not readily available on the internet,
so I used QGIS to synthesize one. I joined an existing shapefile of ISO regions
created by the US Energy Information Administration with a basic state boundaries
shapefile from the US Census Bureau.[^2] [^3] I then used QGIS tools to create a new layer
including properly labeled non-ISO regions. The resulting shapefile, while not perfect,
provides a generally accurate picture of the complex US electricity
landscape.

The Mainland US Map visualization displays the number of projects or amount of
capacity (including storage and generation) waiting in each region's interconnection
queue for time intervals covered by the "Queued Up" dataset. 

### Subtab 2: Bar Chart

The second visualization under the Interconnection Queue by Region tab simply
displays the previous information in a more digestible bar chart format. Note that
the same time and outcome type controls are present in above card.

## Tab 2: Queue Duration by Region

The second tab's visualization shows the typical time spent in the interconnection
queue by completed projects, according to queue exit year. Completed projects include withdrawn and operational
developments---those that were still active on the queue were excluded from this
figure, as the would heavily disrupt the later year values. The typical value can
be toggled between the mean and median residence time.

I included this graphic to demonstrate the interconnection queue times have been
burdensome in recent years, as per the Queued Up report. However, my graph does not
identify an increasing trend particularly well, since delayed projects initiated in
late 2010's and early 2020's have not actually exited the queue yet. Nevertheless, I noted 
important takeaways from this figure. First, there has been more variation in residence
time than I expected since the turn of the millennium. Since sample sizes per year
and region are small, points can also diverge drastically beteween years. Finally,
the interconnection queue process is still clearly lengthy---as of 2022, every region
exhibited a mean residence time of over 500 days.

## Tab 3: Approval Rate by Region

The third graphic shows project approval rate, which is defined as the percent of
development that exit the queue as "operational" rather than "withdrawn" or "suspended".
As with the previous graphic, small sample sizes of completed projects per region
per year seem to cause approval rates to vary wildly between years. Additionally, this
figure made me somewhat wary of the dataset's quality given consistently
perfect approval rates for some regions.

It is notable that the regions with initially high approval rates have experienced 
drops over the past two decades and that most regions have demonstrated a success
percentage below 50% during the 2020's. But to cut through the noise, I added an indicator
for mean approval rate across all regions through the checkbox. This mean approval rate has
remained quite low---generally under 50%---since the late 2000's, indicating that
the interconnection queue might truly be an obstacle to energy development today.

## Conclusions and Future Steps

I found this visualization project to be fulfilling. I enjoyed working with a dataset
close to my professional interest, and I also appreciated the opportunity to conduct
self-directed learning to create the ShinyApp I wanted. And although the data cleaning
process was more intensive than I expected, it presented an interesting challenge
for my non-visualization abilities in R.

Given more time, I would have built more complexity into the existing figures,
adding further interactive elements. I also would have liked to have added more visualizations
to extend the narrative of this project, such as the difference between proposed and
actual approval dates among regions. Future viz projects using this dataset could
utilize more advanced wrangling techniques to eliminate inaccuracies and conduct
joins with other useful electricity-related datasets for deeper analyses.


[^1]: "Queued Up: 2024 Edition, Characteristics of Power Plants Seeking Transmission Interconnection As of the End of 2023." From J. Rand, N. Manderlink, W. Gorman, R. Wiser, J. Seel, J. Kemp, S. Jeong, and F. Karhl, 2024. <https://emp.lbl.gov/queues> 

[^2]: "RTO Region", U.S. Energy Information Administration, 18 February 2025. 
<https://atlas.eia.gov/datasets/eia::rto-regions/explore>

[^3]: "2024 TIGER/Line Shapefiles: States (and equivalent)", U.S. Census Bureau
Geography Division, 2024. <https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2024&layergroup=States+%28and+equivalent%29>